spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: shubhamkarna
    password: 0000
    driver-class-name: org.postgresql.Driver


  application:
    name: SpringSecurityEx

